### PR TITLE
fix: Unintentionally exposed endpoints when enabling github webhooks

### PR DESCRIPTION
**Pull request by casperbiering**
## Description
When following the guide to allow access for github webhooks, then you're actually incorrectly exposing endpoints in the following ways:
1) All endpoints is allowed from github IPs
2) `/events` endpoint is allowed from the entire world

## Motivation and Context
Limiting exposed endpoints is a good security practice.

## Breaking Changes
It shouldn't except:
1) abusing the rules to have github webhooks hit other endpoints than `/events`
2) abusing the `allow_github_webhooks` option to allow webhooks from other systems than github

## How Has This Been Tested?
- [x] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [x] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [x] I have executed `pre-commit run -a` on my pull request

### CODE REVIEW

**Comment by casperbiering** [comment]
This is still relevant

**Comment by casperbiering** [comment]
This is still relevant

**Comment by casperbiering** [comment]
@bryantbiggs @antonbabenko Can you guys review please?

**Comment by dynamike** [comment]
I think the overall intent of this PR is valid, but doesn't appear to work the way I was expecting and after a bit of experimentation, I think I understand why. 

The default behavior of the ALB routing rules is to forward traffic **if** you don't specify an ALB authentication method. 
image

So any forwarding rules limiting `/events` to GitHub only IPs is ignored because by default all traffic is allowed. The only way I think this can be resolved is to have a fixed response (e.g., 401 Unauthorized) either as the default response or as a low priority listener rule.

**Pull request closed without merging**
