### PR TITLE
feat: Additional tags to wide open security groups

### PR DESCRIPTION
**Pull request by nitrocode**
## Description
Adds a new variable `var.tags_sgs_additional` to merge with the tags supplied on the security group resources that are open to the world. This is to add tags to those wide open security groups to pass our audits.

## Motivation and Context
For auditing purposes

Closes https://github.com/terraform-aws-modules/terraform-aws-atlantis/issues/141

## Breaking Changes
None

## How Has This Been Tested?
Locally

### CODE REVIEW

**Comment by bryantbiggs** [comment]
thanks @nitrocode - could you split this up to 3 tags since there are 3 security groups and name them:
- `alb_https_security_group_tags`
- `alb_http_security_group_tags`
- `atlantis_security_group_tags`

and the variables can be defined similar to what has been done on the `vpc` module [here](https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/75a18883c55a709ac8b565557f71ca364701c732/variables.tf#L1722)

**Comment by nitrocode** [comment]
Hi @bryantbiggs .

>- alb_https_security_group_tags
>- alb_http_security_group_tags
>- atlantis_security_group_tags

The way these are named, are you advocating to not do a `merge` on those resources' tags' regarding the `tags` variable and instead supplant `var.tags` for those resources ?

>and the variables can be defined similar to what has been done on the `vpc` module here

If I used the example you linked to, the variable in this PR would be `var.sgs_tags` and would apply to all of the open-to-the-world security groups. Is that correct?

**Comment by bryantbiggs** [comment]
no no, I think merging is good. its common across the modules here, there is a default tags group and then individual tags per "resource". so if you look at like the VPC module as an example, you'll see they merge the default tags as well as tags for the specific resource like:

`var.tags,
    var.dhcp_options_tags,

**Comment by nitrocode** [comment]
@bryantbiggs makes sense to me. I updated the changes to reflect your suggestions.

From previous comments by @antonbabenko, it looks like these PRs won't get any love until August https://github.com/terraform-aws-modules/terraform-aws-atlantis/pull/128#issuecomment-660943650.

**Comment by bryantbiggs** [comment]
@nitrocode would you mind updating your branch with master - @antonbabenko 👍

**Comment by nitrocode** [comment]
All set!

**Comment by antonbabenko** [comment]
Thanks, @nitrocode !

[v2.22.0](https://github.com/terraform-aws-modules/terraform-aws-atlantis/releases/v2.22.0) has been just released.

**Pull request merged**
