### PR TITLE
[WIP] Feature/gitlab

### PR DESCRIPTION
**Pull request by rosscdh**
Splitting module to support gitlab as well

### CODE REVIEW

**Comment by webframp** [comment]
Looking forward to seeing this merged, I was hoping to test out atlantis on Fargate but we also need Gitlab support. Good to know someone was already working on this before I started.

**Comment by rosscdh** [comment]
I've recently deployed it to production on my side, but feel free to ref the branch and see if it works for you. Ill add some docs tomorrow here.

**Comment by antonbabenko** [comment]
Thanks for the PR, but I don't like the idea to maintain 2 pieces of the code which should be 90% the same (GitHub and GitLab).

I will make them combined during today if you don't mind and ask you to verify (I don't want to dive into GitLab specifics just now).

**Comment by antonbabenko** [comment]
Thanks @rosscdh for good PR.

@webframp @JoshiiSinfield Please try [v1.6.0](https://github.com/terraform-aws-modules/terraform-aws-atlantis/releases/v1.6.0) where support for GitLab was added.

Let me know if there are any errors. I have not tried it on GitLab myself.

**Pull request closed without merging**
