### PR TITLE
feat: Enable encrypt function on EFS

### PR DESCRIPTION
**Pull request by titanlien**
## Description

As title

## Motivation and Context

Enable encrypt function on EFS

## Breaking Changes

No

## How Has This Been Tested?
- [ ] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [ ] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [x] I have executed `pre-commit run -a` on my pull request

### CODE REVIEW

**Comment by bryantbiggs** [comment]
@titanlien this looks good - please update with `master` when you get a chance and we can merge

**Comment by titanlien** [comment]
Hi @cytopia I believe you can fetch this upstream and update our PR again.

**Comment by snovikov** [comment]
@bryantbiggs updated

**Review by bryantbiggs — APPROVED** [review]

**Comment by bryantbiggs** [comment]
once you update with `master` we can get this merged, thank you!

**Comment by antonbabenko** [comment]
This PR is included in version 3.21.0 :tada:

**Pull request merged**
