### PR TITLE
feat: Add enable_ecs_managed_tags and propagate_tags arguments to ecs_service

### PR DESCRIPTION
**Pull request by nitrocode**
## Description
Add `enable_ecs_managed_tags` and `propagate_tags` arguments to `aws_ecs_service`

More info here: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecs_service

## Motivation and Context
Tagging tasks

## Breaking Changes
None

## How Has This Been Tested?
Locally

### CODE REVIEW

**Review by bryantbiggs — APPROVED** [review]
looks good - @antonbabenko 👍🏼

**Comment by nitrocode** [comment]
Thanks for the approval @bryantbiggs 

Does the `README.md` have to be manually updated ?

**Comment by bryantbiggs** [comment]
@nitrocode if you have pre-commit installed you can run `pre-commit run -a` and it will update the `README.md` correctly

**Comment by antonbabenko** [comment]
Thanks @nitrocode and @bryantbiggs !

[v2.31.0](https://github.com/terraform-aws-modules/terraform-aws-atlantis/releases/v2.31.0) has been just released.

**Pull request merged**
