### PR TITLE
feat: Add tags to cluster, task, ssm, and role resources

### PR DESCRIPTION
**Pull request by nitrocode**
## Description
Added tags to cluster, task, ssm, role, and fmt

Specifically did not add it to ecs service as this mandates account level new arn format

## Motivation and Context
More tags allows us to track resources down

## Breaking Changes
None

## How Has This Been Tested?
terraform applied locally

### CODE REVIEW

**Comment by nitrocode** [comment]
Hi @antonbabenko ! If you or someone on your team is free, would you please review this?

**Comment by antonbabenko** [comment]
This code looks good to me, but I have no possibility to test it better at the moment. Merging.

PS: "improvement" prefix was removed from supported prefixes in titles by conventional-commit-types (see [this PR](https://github.com/commitizen/conventional-commit-types/commit/958396a7224f6d6530b23998caffe82ddecc16e1)). We use "feat" and "fix" normally.

**Comment by antonbabenko** [comment]
Thanks @nitrocode !

[v2.6.0](https://github.com/terraform-aws-modules/terraform-aws-atlantis/releases/v2.6.0) has been just released.

**Comment by nitrocode** [comment]
Awesome, thank you so much!

**Pull request merged**
