### PR TITLE
Refresh the underlying module to the latest release versions

### PR DESCRIPTION
**Pull request by chenrui333**

### CODE REVIEW

**Comment by chenrui333** [comment]
Causing some error with my `tf plan`:
```
Error: Error running plan: 1 error(s) occurred:

* module.atlantis.module.acm.aws_route53_record.validation: 1 error(s) occurred:

* module.atlantis.module.acm.aws_route53_record.validation: Resource 'aws_acm_certificate.this' not found for variable 'aws_acm_certificate.this.domain_validation_options.0.resource_record_type'
```

**Comment by antonbabenko** [comment]
Looks good, does it work? I mean have you fixed the problem with `module.atlantis.module.acm.aws_route53_record.validation` ?

**Comment by chenrui333** [comment]
@antonbabenko 
yeah, I just realized it is actually irrelevant to this PR, I will try to get my tf-state and test on this PR change.

**Comment by chenrui333** [comment]
I have restarted my flow with `terraform init` and `terraform plan`, indeed re-encounter the same issue:
```
------------------------------------------------------------------------

Error: Error running plan: 1 error(s) occurred:

* module.atlantis.module.acm.aws_route53_record.validation: 1 error(s) occurred:

* module.atlantis.module.acm.aws_route53_record.validation: Resource 'aws_acm_certificate.this' not found for variable 'aws_acm_certificate.this.domain_validation_options.0.resource_record_type'
```

**Comment by antonbabenko** [comment]
I found and fixed the problem. Use ACM module version [v1.1.0](https://github.com/terraform-aws-modules/terraform-aws-acm/releases/v1.1.0).

**Comment by chenrui333** [comment]
Sounds good, going to try now.

**Comment by chenrui333** [comment]
Seems good:
```
------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place
  - destroy
 <= read (data resources)

Terraform will perform the following actions:

 <= module.atlantis.data.aws_ecs_task_definition.atlantis
      id:              <computed>
      family:          <computed>
      network_mode:    <computed>
      revision:        <computed>
      status:          <computed>
      task_definition: "atlantis"
      task_role_arn:   <computed>

  ~ module.atlantis.aws_ecs_service.atlantis
      task_definition: "atlantis:2" => "${data.aws_ecs_task_definition.atlantis.family}:${max(aws_ecs_task_definition.atlantis.revision, data.aws_ecs_task_definition.atlantis.revision)}"

  - module.atlantis.module.acm.aws_route53_record.validation


Plan: 0 to add, 1 to change, 1 to destroy.
```

**Comment by chenrui333** [comment]
@antonbabenko working pretty good for me. Let me know if you need me to do other checks.

**Comment by antonbabenko** [comment]
Sounds great, let's merge it and use it. Thank you!

**Comment by antonbabenko** [comment]
[v1.10.0](https://github.com/terraform-aws-modules/terraform-aws-atlantis/releases/v1.10.0) has been released.

**Pull request merged**
