### PR TITLE
[WIP] feature/ecs_secrets

### PR DESCRIPTION
**Pull request by stephencoe**
Support for ECS secrets using parameter store rather than visible as environment variables. 

https://docs.aws.amazon.com/AmazonECS/latest/developerguide/specifying-sensitive-data.html

### CODE REVIEW

**Comment by antonbabenko** [comment]
It is not possible to use `secrets` in Fargate yet, but I will keep relevant code in place once it becomes available.

More details - https://github.com/aws/amazon-ecs-agent/issues/1209#issuecomment-445984482

**Comment by antonbabenko** [comment]
I've put required code during #27 and merged. Waiting for ECS update to complete this issue.

Thanks for the feature request and initial PR!

**Comment by stephencoe** [comment]
@antonbabenko Thanks for pointing that out, I hadn't seen it wasn't compatible with fargate yet! I will keep an eye out on the functionality being available

**Comment by antonbabenko** [comment]
It should be possible now, according to this - https://aws.amazon.com/about-aws/whats-new/2018/12/aws-fargate-platform-version-1-3-adds-secrets-support/

**Comment by stephencoe** [comment]
Great! So I was wondering if you want to keep support for both environment and the secrets keys so it can be used in either way, if so I will put the switch in to support both.

**Comment by antonbabenko** [comment]
@stephencoe Thanks for the PR!

I have completed it in #28 and released [v1.7.0](https://github.com/terraform-aws-modules/terraform-aws-atlantis/releases/v1.7.0).

Now it is time to celebrate New Year 🎉

**Pull request closed without merging**
