### PR TITLE
fix: add secrets check based on scm source

### PR DESCRIPTION
**Pull request by bmihaescu**
I changed the secrets config to use `secrets_group` value to correctly assign secrets based on the `atlantis_gitlab_user`, `atlantis_github_user` or `atlantis_bitbucket_user` values that are passed to the module. 

Fixes https://github.com/terraform-aws-modules/terraform-aws-atlantis/issues/67

### CODE REVIEW

**Comment by bmihaescu** [comment]
@antonbabenko can you review this pr ? 
It is a blocker for us and we need this to be merged. 

Thanks

**Comment by bryantbiggs** [comment]
hi @bmihaescu - could you please merge master/rebase to update your branch and change your title to something like `fix: add secrets check based on scm source` - thank you!

**Comment by Szasza** [comment]
Hi @bmihaescu , @bryantbiggs and @antonbabenko ,

I hope all is well.

Would it be possible to merge/rebase master again and get this merged?

Thank you all for the contribution and maintenance, it is greatly appreciated!

**Comment by antonbabenko** [comment]
@Szasza I didn't have time to look into this issue myself, but earlier today there was a new release [v2.24.0](https://github.com/terraform-aws-modules/terraform-aws-atlantis/releases/v2.24.0) of this module which touched the same variables as this one (#151).

Regarding this PR, I am not sure how adding another set of conditions is making it good. Can it be simplified instead of adding more cases after rebase?

@bryantbiggs Please let us know what do you think? Hopefully, you use this more than me lately :)

**Comment by bryantbiggs** [comment]
I'll try to take a look this week - the conditional checks have been getting a bit unwieldy!

**Comment by Szasza** [comment]
@antonbabenko @bryantbiggs awesome, thanks to both of you, it is greatly appreciated!

**Pull request closed without merging**
