### PR TITLE
fix: Fix the GitHub Complete example

### PR DESCRIPTION
**Pull request by skalinets**
## Description
The [GitHub Complete example](https://github.com/terraform-aws-modules/terraform-aws-atlantis/tree/master/examples/github-complete) is broken because of #253. This PR fixes it.

## Motivation and Context
I spend few hour trying to provision the Atlantis to Fargate with no luck. Then I found #253 and realised what was the issue. With these fixes everything executed without errors. 

## Breaking Changes
This PR touches only examples folder, so I don't think it will introduce any breaking change.

## How Has This Been Tested?
- [x] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [x] I have tested and validated these changes using one or more of the provided `examples/*` project
- [x] I have executed `pre-commit run -a` on my pull request

### CODE REVIEW

**Review by antonbabenko — CHANGES_REQUESTED** [review]
Looks good. Could you also add `github_repo_names` into [terraform.tfvars.sample](https://github.com/terraform-aws-modules/terraform-aws-atlantis/blob/master/examples/github-complete/terraform.tfvars.sample)?

**Comment by skalinets** [comment]
I also noticed that despite the webhook has been created, when PR change is made Atlantis  posts the following comment:

> Error: This repo is not allowlisted for Atlantis.

Will investigate and fix.

**Comment by skalinets** [comment]
> Looks good. Could you also add `github_repo_names` into [terraform.tfvars.sample](https://github.com/terraform-aws-modules/terraform-aws-atlantis/blob/master/examples/github-complete/terraform.tfvars.sample)?

done. 

I fixed issue with the error message. There is an obvious ambiguity in the meaning of `atlantis_repo_allowlist` in different modules as discussed in #253, I think [this one](https://github.com/terraform-aws-modules/terraform-aws-atlantis/blob/master/modules/github-repository-webhook/variables.tf#L25) should be renamed to `github_repos` or something. However I'd prefer to limit the scope of this PR to the `examples` directory :)

**Comment by antonbabenko** [comment]
This PR is included in version 3.15.1 :tada:

**Pull request merged**
